version: "3.9"
# RED DEL PROYECTO
networks:
  lemoncode-network:
    driver: bridge

# (persistencia de datos)
volumes:
  mongo_data:

# SERVICIOS
services:

  # MONGO DB (Base de datos)
  mongo:
    image: mongo:4.4 # 4.4 por la versión por compatibilidad con mi ordenador
    container_name: mongo

    # Puerto estándar de MongoDB
    ports:
      - "27017:27017"

    # Persistencia de datos
    volumes:
      - mongo_data:/data/db

    # Conectado a la red
    networks:
      - lemoncode-network
    # Reinicio automático si falla
    restart: always
  # BACKEND (API Node.js)
  topics-api:
    build:
      context: ./backend   # ruta del Dockerfile del backend

    container_name: topics-api

    ports:
      - "5000:5000"

    # Variables de entorno para conectar con MongoDB
    environment:
      DATABASE_URL: mongodb://mongo:27017
      DATABASE_NAME: ClassesDb
      PORT: 5000

    # Espera a que Mongo este encendido
    depends_on:
      - mongo

    networks:
      - lemoncode-network

    restart: always


    # FRONTEND   
  frontend:
    build:
      context: ./frontend   # ruta del Dockerfile del frontend

    container_name: frontend

    ports:
      - "3000:3000"

    # URL del backend dentro de Docker
    environment:
      API_URL: http://topics-api:5000/api/classes

    depends_on:
      - topics-api

    networks:
      - lemoncode-network

    restart: always
